### ISSUE TITLE
Trouble building on an Ampro LB, and Z80AS not producing the same output as ZAS

### ISSUE THREAD

**Issue by mecparts** [Laci1953/Z80AS#2]
Using a 58K Ampro LB/Z80, I tried building everything from source and ran into some problems.

* Assembling eval.as and macros.as gave a "Can't open include file ZSM.INC" error.

This seems to be ZAS speak for "I ran out of memory someplace I didn't expect to". Inlining the include file got around the error. On the 62K system sitting next to the Ampro, both files assembled correctly unless I tried to batch everything using ZEX. By doing everything one at a time from the command line worked fine.

* Assembling zsm6.as gave an "Out of memory" error.

Inlining ZSM.INC didn't help here. I eventually resorted to stripping out all the comments, and converting runs of spaces in the code to tabs, which returned the file size from 80K to 24K. That got it to assemble on the 62K system, but still not on the 58K Ampro.

With all that out of the way, I was able (on the 62K system) to link a Z80AS.COM that (save for the unititalized 'defs' portions) matched up with the COM file produced by MLOAD'ing Z80AS.HEX.

Next, I tried re-assembling all the source files using Z80AS rather than ZAS. Everything assembled on the 58K Ampro this time. But the Z80AS's OBJ files all had different sizes (and CRCs) than the OBJ files created by ZAS. The COM file was different as well; and it didn't work. Trying to assemble the source with this version (Z80AS assembled with Z80AS) crashed creatively.

I've only been tinkering with this for an afternoon, so it's entirely possible that it can all be chalked up to new user error but I thought I'd throw it out there in case anyone else is seeing weirdness.

**Comment by Laci1953** [comment]
Hi,
problem found, issue opened in GitHub, working on the fix...
thx,Ladislau
    On Friday, January 21, 2022, 03:14:57 AM GMT+2, mecparts ***@***.***> wrote:  
 
 


Using a 58K Ampro LB/Z80, I tried building everything from source and ran into some problems.
   
   - Assembling eval.as and macros.as gave a "Can't open include file ZSM.INC" error.

This seems to be ZAS speak for "I ran out of memory someplace I didn't expect to". Inlining the include file got around the error. On the 62K system sitting next to the Ampro, both files assembled correctly unless I tried to batch everything using ZEX. By doing everything one at a time from the command line worked fine.
   
   - Assembling zsm6.as gave an "Out of memory" error.

Inlining ZSM.INC didn't help here. I eventually resorted to stripping out all the comments, and converting runs of spaces in the code to tabs, which returned the file size from 80K to 24K. That got it to assemble on the 62K system, but still not on the 58K Ampro.

With all that out of the way, I was able (on the 62K system) to link a Z80AS.COM that (save for the unititalized 'defs' portions) matched up with the COM file produced by MLOAD'ing Z80AS.HEX.

Next, I tried re-assembling all the source files using Z80AS rather than ZAS. Everything assembled on the 58K Ampro this time. But the Z80AS's OBJ files all had different sizes (and CRCs) than the OBJ files created by ZAS. The COM file was different as well; and it didn't work. Trying to assemble the source with this version (Z80AS assembled with Z80AS) crashed creatively.

I've only been tinkering with this for an afternoon, so it's entirely possible that it can all be chalked up to new user error but I thought I'd throw it out there in case anyone else is seeing weirdness.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Laci1953** [comment]
FIXED; I changed make.sub (now, Z80AS is assembled using Z80AS ! )
Yes, a self assembling assembler :)

**Comment by Laci1953** [comment]
fixed, thx,Ladislau

    On Friday, January 21, 2022, 06:44:09 AM GMT+2, Ladislau Szilagyi ***@***.***> wrote:  
 
  Hi,
problem found, issue opened in GitHub, working on the fix...
thx,Ladislau
    On Friday, January 21, 2022, 03:14:57 AM GMT+2, mecparts ***@***.***> wrote:  
 
 


Using a 58K Ampro LB/Z80, I tried building everything from source and ran into some problems.
   
   - Assembling eval.as and macros.as gave a "Can't open include file ZSM.INC" error.

This seems to be ZAS speak for "I ran out of memory someplace I didn't expect to". Inlining the include file got around the error. On the 62K system sitting next to the Ampro, both files assembled correctly unless I tried to batch everything using ZEX. By doing everything one at a time from the command line worked fine.
   
   - Assembling zsm6.as gave an "Out of memory" error.

Inlining ZSM.INC didn't help here. I eventually resorted to stripping out all the comments, and converting runs of spaces in the code to tabs, which returned the file size from 80K to 24K. That got it to assemble on the 62K system, but still not on the 58K Ampro.

With all that out of the way, I was able (on the 62K system) to link a Z80AS.COM that (save for the unititalized 'defs' portions) matched up with the COM file produced by MLOAD'ing Z80AS.HEX.

Next, I tried re-assembling all the source files using Z80AS rather than ZAS. Everything assembled on the 58K Ampro this time. But the Z80AS's OBJ files all had different sizes (and CRCs) than the OBJ files created by ZAS. The COM file was different as well; and it didn't work. Trying to assemble the source with this version (Z80AS assembled with Z80AS) crashed creatively.

I've only been tinkering with this for an afternoon, so it's entirely possible that it can all be chalked up to new user error but I thought I'd throw it out there in case anyone else is seeing weirdness.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mecparts** [comment]
That works very nicely now.

As a check, I wanted to compare the output of assembling Z80AS with ZAS and Z80AS. I found a better way of assembling zsm6.as with ZAS; I split the file into 2 parts at the opcode table, and added the include and globals to the second part. ZAS was then able to assemble both parts on the 62K system.

Other than some insignificant differences in the uninitialised data section, the COM files produced by ZAS and Z80AS are byte for byte identical. I think you've killed the bug in genobj.as dead!
