### ISSUE TITLE
Error in a relative jump in Z80AS.AS

### ISSUE THREAD

**Issue by agl7** [Laci1953/Z80AS#8]
Hello Ladislau Szilagyi,

I found an error in the source of the Z80AS.AS (uploaded 4 days ago). During assembly an error is displayed for a relative jump. The source says 'xjr' instead of 'jr'. The error is marked with 'N' (Illegal opcode) and between the labels 'seeovrld:' and 'seeabs:'.

Best regards
Andreas (agl7)

**Comment by Laci1953** [comment]
Fixed ( that 'x' got inserted probably when I prepared the files for upload...)

**Comment by Laci1953** [comment]
Fixed,
thx,Ladislau
    On Wednesday, March 30, 2022, 08:10:18 PM GMT+3, Dipl.-Ing. (FH) Andreas Gerlich ***@***.***> wrote:  
 
 


Hello Ladislau Szilagyi,

I found an error in the source of the Z80AS.AS (uploaded 4 days ago). During assembly an error is displayed for a relative jump. The source says 'xjr' instead of 'jr'. The error is marked with 'N' (Illegal opcode) and between the labels 'seeovrld:' and 'seeabs:'.

Best regards
Andreas (agl7)
